package com.samsung.android.knox.zt.config.securelog;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/* compiled from: qb/89523975 2c9f6d15a1195540f21380d26e2599d2824bfc1ae85110b01296b5f4d9a9b658 */
/* loaded from: classes4.dex */
public class SignalName {
    public static final String ACCESSIBILITY_EVENT = "ACCESSIBILITY_EVENT";
    public static final String ACCESS_CALL_LOG_PERMISSION = "ACCESS_CALL_LOG_PERMISSION";
    public static final String ACCESS_NOTIFICATION_PERMISSION = "ACCESS_NOTIFICATION_PERMISSION";
    public static final String BOOT_COMPROMISED_SOFTWARE_BINARY =
            "BOOT_COMPROMISED_SOFTWARE_BINARY";
    public static final String BOOT_SECURITY_ABNORMALITY = "BOOT_SECURITY_ABNORMALITY";
    public static final String BOOT_STATE = "BOOT_STATE";
    public static final String KEY_INPUT_CAPTURE_CAPABILITY = "KEY_INPUT_CAPTURE_CAPABILITY";
    public static final String LOG_IS_FULL = "LOG_IS_FULL";
    public static final String PASSWORD_LOCKOUT = "PASSWORD_LOCKOUT";
    public static final String PERIPHERAL_ACCESS_THROUGH_POLICY_DETECTED_CAMERA =
            "PERIPHERAL_ACCESS_THROUGH_POLICY_DETECTED_CAMERA";
    public static final String PERIPHERAL_ACCESS_THROUGH_POLICY_DETECTED_MIC =
            "PERIPHERAL_ACCESS_THROUGH_POLICY_DETECTED_MIC";
    public static final String PREVENT_APP_REMOVAL_CAPABILITY = "PREVENT_APP_REMOVAL_CAPABILITY";
    public static final String PROACTIVE_PHISHING_DETECTION = "PROACTIVE_PHISHING_DETECTION";
    public static final String PROCESS_CREATION = "PROCESS_CREATION";
    public static final String PROCESS_PERMISSIONS_MODIFICATION =
            "PROCESS_PERMISSIONS_MODIFICATION";
    public static final String PROCESS_PRIVILEGE_ESCALATION = "PROCESS_PRIVILEGE_ESCALATION";
    public static final String PROCESS_TERMINATION = "PROCESS_TERMINATION";
    public static final String REMOTE_CONTROL_API_USED = "REMOTE_CONTROL_API_USED";
    public static final String RESTRICTED_PERMISSION = "RESTRICTED_PERMISSION";
    public static final String SCREEN_CAPTURE_CAPABILITY = "SCREEN_CAPTURE_CAPABILITY";
    public static final String SOCKET_CREATION = "SOCKET_CREATION";
    public static final String SOCKET_TERMINATION = "SOCKET_TERMINATION";
    public static final String SOCKET_UPDATE = "SOCKET_UPDATE";
    public static final String SUSPICIOUS_URL_ACCESSED = "SUSPICIOUS_URL_ACCESSED";
    public static final String SUSPICIOUS_URL_DETECTED = "SUSPICIOUS_URL_DETECTED";
    public static final String TAG_ADB_SHELL_CMD = "TAG_ADB_SHELL_CMD";
    public static final String TAG_ADB_SHELL_INTERACTIVE = "TAG_ADB_SHELL_INTERACTIVE";
    public static final String TAG_ADD_UNTRUSTED = "TAG_ADD_UNTRUSTED";
    public static final String TAG_ADMIN_HAS_ADDED_SSID_TO_THE_RESTRICTION_ALLOWLIST =
            "TAG_ADMIN_HAS_ADDED_SSID_TO_THE_RESTRICTION_ALLOWLIST";
    public static final String TAG_ADMIN_HAS_ADDED_SSID_TO_THE_RESTRICTION_BLOCKLIST =
            "TAG_ADMIN_HAS_ADDED_SSID_TO_THE_RESTRICTION_BLOCKLIST";
    public static final String TAG_ADMIN_HAS_ADDED_TO_APP_SIGNATURE_ALLOWLIST =
            "TAG_ADMIN_HAS_ADDED_TO_APP_SIGNATURE_ALLOWLIST";
    public static final String TAG_ADMIN_HAS_ADDED_TO_APP_SIGNATURE_BLOCKLIST =
            "TAG_ADMIN_HAS_ADDED_TO_APP_SIGNATURE_BLOCKLIST";
    public static final String TAG_ADMIN_HAS_ADDED_TO_CAMERA_ALLOWLIST =
            "TAG_ADMIN_HAS_ADDED_TO_CAMERA_ALLOWLIST";
    public static final String TAG_ADMIN_HAS_ALLOWED_ACCESS_TO_WIFI_SSID =
            "TAG_ADMIN_HAS_ALLOWED_ACCESS_TO_WIFI_SSID";
    public static final String TAG_ADMIN_HAS_ALLOWED_CAMERA = "TAG_ADMIN_HAS_ALLOWED_CAMERA";
    public static final String TAG_ADMIN_HAS_ALLOWED_MICROPHONE =
            "TAG_ADMIN_HAS_ALLOWED_MICROPHONE";
    public static final String TAG_ADMIN_HAS_ALLOWED_TO_INSTALL_APPLICATION =
            "TAG_ADMIN_HAS_ALLOWED_TO_INSTALL_APPLICATION";
    public static final String TAG_ADMIN_HAS_CHANGED_LOCK_SCREEN_STATE_TO_DISABLED =
            "TAG_ADMIN_HAS_CHANGED_LOCK_SCREEN_STATE_TO_DISABLED";
    public static final String TAG_ADMIN_HAS_CHANGED_LOCK_SCREEN_STATE_TO_ENABLED =
            "TAG_ADMIN_HAS_CHANGED_LOCK_SCREEN_STATE_TO_ENABLED";
    public static final String TAG_ADMIN_HAS_CHANGED_NFC_STATE_CHANGE =
            "TAG_ADMIN_HAS_CHANGED_NFC_STATE_CHANGE";
    public static final String TAG_ADMIN_HAS_CHANGED_SCREEN_LOCK_TIME_OUT =
            "TAG_ADMIN_HAS_CHANGED_SCREEN_LOCK_TIME_OUT";
    public static final String TAG_ADMIN_HAS_CHANGED_WIFI_ALLOWED =
            "TAG_ADMIN_HAS_CHANGED_WIFI_ALLOWED";
    public static final String TAG_ADMIN_HAS_CHANGED_WIFI_SSID_RESTRICTION_ENABLE =
            "TAG_ADMIN_HAS_CHANGED_WIFI_SSID_RESTRICTION_ENABLE";
    public static final String TAG_ADMIN_HAS_CHANGED_WIFI_STATE_CHANGE_ALLOWED =
            "TAG_ADMIN_HAS_CHANGED_WIFI_STATE_CHANGE_ALLOWED";
    public static final String TAG_ADMIN_HAS_DISABLED_BLUETOOTH_DISCOVERABLE_STATE =
            "TAG_ADMIN_HAS_DISABLED_BLUETOOTH_DISCOVERABLE_STATE";
    public static final String TAG_ADMIN_HAS_DISABLED_WIFI_DIRECT =
            "TAG_ADMIN_HAS_DISABLED_WIFI_DIRECT";
    public static final String TAG_ADMIN_HAS_DISABLED_WIFI_TETHERING_SETTING =
            "TAG_ADMIN_HAS_DISABLED_WIFI_TETHERING_SETTING";
    public static final String TAG_ADMIN_HAS_DISALLOWED_CAMERA = "TAG_ADMIN_HAS_DISALLOWED_CAMERA";
    public static final String TAG_ADMIN_HAS_DISALLOWED_MICROPHONE =
            "TAG_ADMIN_HAS_DISALLOWED_MICROPHONE";
    public static final String TAG_ADMIN_HAS_DISALLOWED_TO_INSTALL_APPLICATION =
            "TAG_ADMIN_HAS_DISALLOWED_TO_INSTALL_APPLICATION";
    public static final String TAG_ADMIN_HAS_ENABLED_BLUETOOTH_DISCOVERABLE_STATE =
            "TAG_ADMIN_HAS_ENABLED_BLUETOOTH_DISCOVERABLE_STATE";
    public static final String TAG_ADMIN_HAS_ENABLED_WIFI_DIRECT =
            "TAG_ADMIN_HAS_ENABLED_WIFI_DIRECT";
    public static final String TAG_ADMIN_HAS_ENABLED_WIFI_TETHERING_SETTING =
            "TAG_ADMIN_HAS_ENABLED_WIFI_TETHERING_SETTING";
    public static final String TAG_ADMIN_HAS_LOCKED_WORKSPACE = "TAG_ADMIN_HAS_LOCKED_WORKSPACE";
    public static final String TAG_ADMIN_HAS_REMOVED_ALL_SSIDS_FROM_THE_RESTRICTION_ALLOWLIST =
            "TAG_ADMIN_HAS_REMOVED_ALL_SSIDS_FROM_THE_RESTRICTION_ALLOWLIST";
    public static final String TAG_ADMIN_HAS_REMOVED_ALL_SSID_FROM_THE_RESTRICTION_BLOCKLIST =
            "TAG_ADMIN_HAS_REMOVED_ALL_SSID_FROM_THE_RESTRICTION_BLOCKLIST";
    public static final String TAG_ADMIN_HAS_REMOVED_FROM_APP_SIGNATURE_ALLOWLIST =
            "TAG_ADMIN_HAS_REMOVED_FROM_APP_SIGNATURE_ALLOWLIST";
    public static final String TAG_ADMIN_HAS_REMOVED_FROM_APP_SIGNATURE_BLOCKLIST =
            "TAG_ADMIN_HAS_REMOVED_FROM_APP_SIGNATURE_BLOCKLIST";
    public static final String TAG_ADMIN_HAS_REMOVED_FROM_CAMERA_ALLOWLIST =
            "TAG_ADMIN_HAS_REMOVED_FROM_CAMERA_ALLOWLIST";
    public static final String TAG_ADMIN_HAS_REMOVED_SSID_FROM_THE_RESTRICTION_ALLOWLIST =
            "TAG_ADMIN_HAS_REMOVED_SSID_FROM_THE_RESTRICTION_ALLOWLIST";
    public static final String TAG_ADMIN_HAS_REMOVED_SSID_FROM_THE_RESTRICTION_BLOCKLIST =
            "TAG_ADMIN_HAS_REMOVED_SSID_FROM_THE_RESTRICTION_BLOCKLIST";
    public static final String TAG_ADMIN_HAS_REQUESTED_FULL_WIPE_OF_DEVICE =
            "TAG_ADMIN_HAS_REQUESTED_FULL_WIPE_OF_DEVICE";
    public static final String TAG_ADMIN_HAS_SET_NEW_WIFI_PROFILE_SSID_SECURITY_TYPE =
            "TAG_ADMIN_HAS_SET_NEW_WIFI_PROFILE_SSID_SECURITY_TYPE";
    public static final String TAG_ADMIN_HAS_STARTED_GPS = "TAG_ADMIN_HAS_STARTED_GPS";
    public static final String TAG_ADMIN_HAS_STOPPED_GPS = "TAG_ADMIN_HAS_STOPPED_GPS";
    public static final String TAG_ADMIN_HAS_SUCCESSFULLY_LOCKED_WORKSPACE =
            "TAG_ADMIN_HAS_SUCCESSFULLY_LOCKED_WORKSPACE";
    public static final String TAG_ADMIN_HAS_SUCCESSFULLY_UNLOCKED_WORKSPACE =
            "TAG_ADMIN_HAS_SUCCESSFULLY_UNLOCKED_WORKSPACE";
    public static final String TAG_ADMIN_HAS_UNLOCKED_WORKSPACE =
            "TAG_ADMIN_HAS_UNLOCKED_WORKSPACE";
    public static final String
            TAG_APPLICATION_ACTION_FAILED_BECAUSE_OF_SIGNATURE_VERIFICATION_FAILURE =
                    "TAG_APPLICATION_ACTION_FAILED_BECAUSE_OF_SIGNATURE_VERIFICATION_FAILURE";
    public static final String TAG_APPLICATION_INSTALLATION_ALLOWED_BY_ADMIN_ALLOWLIST =
            "TAG_APPLICATION_INSTALLATION_ALLOWED_BY_ADMIN_ALLOWLIST";
    public static final String TAG_APPLICATION_INSTALLATION_ALLOWED_BY_ADMIN_INSTALLER_ALLOWLIST =
            "TAG_APPLICATION_INSTALLATION_ALLOWED_BY_ADMIN_INSTALLER_ALLOWLIST";
    public static final String
            TAG_APPLICATION_INSTALLATION_NOT_ALLOWED_BECAUSE_SIGNED_UNTRUSTED_CA =
                    "TAG_APPLICATION_INSTALLATION_NOT_ALLOWED_BECAUSE_SIGNED_UNTRUSTED_CA";
    public static final String TAG_APPLICATION_INSTALLATION_NOT_ALLOWED_BY_ADMIN_BLOCKLIST =
            "TAG_APPLICATION_INSTALLATION_NOT_ALLOWED_BY_ADMIN_BLOCKLIST";
    public static final String
            TAG_APPLICATION_INSTALLATION_NOT_ALLOWED_BY_ADMIN_INSTALLER_BLOCKLIST =
                    "TAG_APPLICATION_INSTALLATION_NOT_ALLOWED_BY_ADMIN_INSTALLER_BLOCKLIST";
    public static final String TAG_APP_PROCESS_START = "TAG_APP_PROCESS_START";
    public static final String TAG_BACKUP_SERVICE_TOGGLED = "TAG_BACKUP_SERVICE_TOGGLED";
    public static final String TAG_BIND_TO_VPN_FAILED_COULD_NOT_FIND_PACKAGE =
            "TAG_BIND_TO_VPN_FAILED_COULD_NOT_FIND_PACKAGE";
    public static final String TAG_BIND_TO_VPN_VENDOR_SERVICE_FAILED =
            "TAG_BIND_TO_VPN_VENDOR_SERVICE_FAILED";
    public static final String TAG_BIND_TO_VPN_VENDOR_SERVICE_SUCCESSFULLY =
            "TAG_BIND_TO_VPN_VENDOR_SERVICE_SUCCESSFULLY";
    public static final String TAG_BLUETOOTH_CONNECTION = "TAG_BLUETOOTH_CONNECTION";
    public static final String TAG_BLUETOOTH_DISCONNECTION = "TAG_BLUETOOTH_DISCONNECTION";
    public static final String TAG_CAMERA_POLICY_SET = "TAG_CAMERA_POLICY_SET";
    public static final String TAG_CERT_AUTHORITY_INSTALLED = "TAG_CERT_AUTHORITY_INSTALLED";
    public static final String TAG_CERT_AUTHORITY_REMOVED = "TAG_CERT_AUTHORITY_REMOVED";
    public static final String TAG_CERT_VALIDATION_FAILURE = "TAG_CERT_VALIDATION_FAILURE";
    public static final String TAG_CONNECTING_VPN_TO_SERVER_ADDRESS_FROM_TYPE_FAILED =
            "TAG_CONNECTING_VPN_TO_SERVER_ADDRESS_FROM_TYPE_FAILED";
    public static final String TAG_CONNECTING_VPN_TO_SERVER_ADDRESS_FROM_TYPE_SUCCEEDED =
            "TAG_CONNECTING_VPN_TO_SERVER_ADDRESS_FROM_TYPE_SUCCEEDED";
    public static final String TAG_CRYPTO_SELF_TEST_COMPLETED = "TAG_CRYPTO_SELF_TEST_COMPLETED";
    public static final String TAG_DATA_DISABLING = "TAG_DATA_DISABLING";
    public static final String TAG_DATA_ENABLING = "TAG_DATA_ENABLING";
    public static final String TAG_DISCONNECTING_VPN_TO_SERVER_ADDRESS_FROM_TYPE =
            "TAG_DISCONNECTING_VPN_TO_SERVER_ADDRESS_FROM_TYPE";
    public static final String TAG_ERROR_OCCURRED_WHILE_VALIDATING_PROFILE_INFORMATION_FOR_VENDOR =
            "TAG_ERROR_OCCURRED_WHILE_VALIDATING_PROFILE_INFORMATION_FOR_VENDOR";
    public static final String TAG_FAILED_TO_WIPE_USER_DATA = "TAG_FAILED_TO_WIPE_USER_DATA";
    public static final String TAG_KEYGUARD_DISABLED_FEATURES_SET =
            "TAG_KEYGUARD_DISABLED_FEATURES_SET";
    public static final String TAG_KEYGUARD_DISMISSED = "TAG_KEYGUARD_DISMISSED";
    public static final String TAG_KEYGUARD_DISMISS_AUTH_ATTEMPT =
            "TAG_KEYGUARD_DISMISS_AUTH_ATTEMPT";
    public static final String TAG_KEYGUARD_SECURED = "TAG_KEYGUARD_SECURED";
    public static final String TAG_KEY_DESTRUCTION = "TAG_KEY_DESTRUCTION";
    public static final String TAG_KEY_GENERATED = "TAG_KEY_GENERATED";
    public static final String TAG_KEY_IMPORT = "TAG_KEY_IMPORT";
    public static final String TAG_KEY_INTEGRITY_VIOLATION = "TAG_KEY_INTEGRITY_VIOLATION";
    public static final String TAG_LOGGING_STARTED = "TAG_LOGGING_STARTED";
    public static final String TAG_LOGGING_STOPPED = "TAG_LOGGING_STOPPED";
    public static final String TAG_LOG_BUFFER_SIZE_CRITICAL = "TAG_LOG_BUFFER_SIZE_CRITICAL";
    public static final String TAG_MAX_PASSWORD_ATTEMPTS_SET = "TAG_MAX_PASSWORD_ATTEMPTS_SET";
    public static final String TAG_MAX_SCREEN_LOCK_TIMEOUT_SET = "TAG_MAX_SCREEN_LOCK_TIMEOUT_SET";
    public static final String TAG_MEDIA_MOUNT = "TAG_MEDIA_MOUNT";
    public static final String TAG_MEDIA_UNMOUNT = "TAG_MEDIA_UNMOUNT";
    public static final String TAG_MICROPHONE_DISABLED = "TAG_MICROPHONE_DISABLED";
    public static final String TAG_MICROPHONE_ENABLED = "TAG_MICROPHONE_ENABLED";
    public static final String TAG_NETWORK_EVENT_ABNORMAL_PACKET =
            "TAG_NETWORK_EVENT_ABNORMAL_PACKET";
    public static final String TAG_NETWORK_EVENT_INSECURE_PACKET =
            "TAG_NETWORK_EVENT_INSECURE_PACKET";
    public static final String TAG_NETWORK_EVENT_LOCAL_NW_PACKET =
            "TAG_NETWORK_EVENT_LOCAL_NW_PACKET";
    public static final String TAG_OS_SHUTDOWN = "TAG_OS_SHUTDOWN";
    public static final String TAG_OS_STARTUP = "TAG_OS_STARTUP";
    public static final String TAG_PACKAGE_INSTALLED = "TAG_PACKAGE_INSTALLED";
    public static final String TAG_PACKAGE_NAME_HAS_BEEN_ACTIVATED_AS_ADMIN =
            "TAG_PACKAGE_NAME_HAS_BEEN_ACTIVATED_AS_ADMIN";
    public static final String TAG_PACKAGE_NAME_HAS_BEEN_REMOVED_AS_ADMIN =
            "TAG_PACKAGE_NAME_HAS_BEEN_REMOVED_AS_ADMIN";
    public static final String TAG_PACKAGE_UNINSTALLED = "TAG_PACKAGE_UNINSTALLED";
    public static final String TAG_PACKAGE_UPDATED = "TAG_PACKAGE_UPDATED";
    public static final String TAG_PASSWORD_CHANGED = "TAG_PASSWORD_CHANGED";
    public static final String TAG_PASSWORD_COMPLEXITY_REQUIRED =
            "TAG_PASSWORD_COMPLEXITY_REQUIRED";
    public static final String TAG_PASSWORD_COMPLEXITY_SET = "TAG_PASSWORD_COMPLEXITY_SET";
    public static final String TAG_PASSWORD_EXPIRATION_SET = "TAG_PASSWORD_EXPIRATION_SET";
    public static final String TAG_PASSWORD_HISTORY_LENGTH_SET = "TAG_PASSWORD_HISTORY_LENGTH_SET";
    public static final String TAG_REMOTE_LOCK = "TAG_REMOTE_LOCK";
    public static final String TAG_REMOVE_UNTRUSTED = "TAG_REMOVE_UNTRUSTED";
    public static final String TAG_SETTING_BLUETOOTH_DEVICE_AS_DISCOVERABLE_SUCCEEDED =
            "TAG_SETTING_BLUETOOTH_DEVICE_AS_DISCOVERABLE_SUCCEEDED";
    public static final String TAG_SYNC_RECV_FILE = "TAG_SYNC_RECV_FILE";
    public static final String TAG_SYNC_SEND_FILE = "TAG_SYNC_SEND_FILE";
    public static final String TAG_USER_INTERACTION_DISABLING_BLUETOOTH_SUCCEEDED =
            "TAG_USER_INTERACTION_DISABLING_BLUETOOTH_SUCCEEDED";
    public static final String
            TAG_USER_INTERACTION_DISCOVERABLE_MODE_STATUS_HAS_FAILED_TO_CHANGE_REASON_MDM_POLICY =
                    "TAG_USER_INTERACTION_DISCOVERABLE_MODE_STATUS_HAS_FAILED_TO_CHANGE_REASON_MDM_POLICY";
    public static final String TAG_USER_INTERACTION_ENABLING_BLUETOOTH_SUCCEEDED =
            "TAG_USER_INTERACTION_ENABLING_BLUETOOTH_SUCCEEDED";
    public static final String
            TAG_USER_INTERACTION_STATUS_HAS_SUCCESSFULLY_CHANGED_TO_DISCOVERABLE =
                    "TAG_USER_INTERACTION_STATUS_HAS_SUCCESSFULLY_CHANGED_TO_DISCOVERABLE";
    public static final String
            TAG_USER_INTERACTION_STATUS_HAS_SUCCESSFULLY_CHANGED_TO_NOT_DISCOVERABLE =
                    "TAG_USER_INTERACTION_STATUS_HAS_SUCCESSFULLY_CHANGED_TO_NOT_DISCOVERABLE";
    public static final String TAG_USER_RESTRICTION_ADDED = "TAG_USER_RESTRICTION_ADDED";
    public static final String TAG_USER_RESTRICTION_REMOVED = "TAG_USER_RESTRICTION_REMOVED";
    public static final String TAG_WIFI_CONNECTION = "TAG_WIFI_CONNECTION";
    public static final String TAG_WIFI_DISABLING = "TAG_WIFI_DISABLING";
    public static final String TAG_WIFI_DISCONNECTION = "TAG_WIFI_DISCONNECTION";
    public static final String TAG_WIFI_ENABLING = "TAG_WIFI_ENABLING";
    public static final String TAG_WIPE_FAILURE = "TAG_WIPE_FAILURE";
    public static final String TAG_WIPING_DATA_IS_NOT_ALLOWED_FOR_THIS_USER =
            "TAG_WIPING_DATA_IS_NOT_ALLOWED_FOR_THIS_USER";
    public static final String USER_INTERACTION_CONTROL_CAPABILITY =
            "USER_INTERACTION_CONTROL_CAPABILITY";
    public static final String VIDEO_CAPTURE_PERMISSION = "VIDEO_CAPTURE_PERMISSION";

    /* compiled from: qb/89523975 2c9f6d15a1195540f21380d26e2599d2824bfc1ae85110b01296b5f4d9a9b658 */
    @Retention(RetentionPolicy.RUNTIME)
    public @interface SignalNameType {}
}
